    name: Newman API Tests
    on:
    workflow_dispatch:
        jobs:
            test:
                defaults:
    run:
    working-directory: ./test
    environment: staging
    name: 'Run tests'
    runs-on: ubuntu-latest
    steps:

        Github Action Postman 4

        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
    
        with:
    node-version: '18'
      
    - name: 'Install newman'
    run: 'npm install -g newman'

    - name: 'Install newman reporter'
    run: 'npm install -g newman-reporter-htmlextra'

    - name: 'Run tests'
    run: 'newman run KasirAja.postman_collection.json -e TestingEnv.postman_environment.json -r htmlextra --reporter-htmlextra-export htmlrepor.html --reporter-htmlextra-darktheme > runreport1.html'
